### ISSUE TITLE
Add a validity check?

### ISSUE THREAD

**Issue by PentalginPlus** [Hedgefog/cs-snow-wars#2]
AMX Mod X 1.10.0.5435
ReGameDLL version: 5.21.0.546-dev
ReHLDS version: 3.11.0.776-dev

`L 05/20/2022 - 20:43:56: [ReAPI] get_member_s: invalid or uninitialized entity`
`L 05/20/2022 - 20:43:56: [AMXX] Displaying debug trace (plugin "sw_gamemode.amxx", version "0.9.1")`
`L 05/20/2022 - 20:43:56: [AMXX] Run time error 10: native error (native "get_member_s")`
`L 05/20/2022 - 20:43:56: [AMXX]    [0] sw_gamemode.sma::@Player_DropItems (line 118)`
`L 05/20/2022 - 20:43:56: [AMXX]    [1] sw_gamemode.sma::client_disconnected (line 32)`

**Comment by Hedgefog** [comment]
Fixed
